### ISSUE TITLE
./src/components/Banner/banner.js Module not found: Can't resolve 'react-jss'

### ISSUE THREAD

**Issue by sourabhgrover** [React-Chandigarh/reactchandigarh.dev#17]
@sarabs3 @sahildhiman  I am getting this error during npm start.
Is this reproducible on your end too?
![jss](https://user-images.githubusercontent.com/4996935/72372112-c49d8380-372b-11ea-8b3b-d1751ff54ef4.png)
![2](https://user-images.githubusercontent.com/4996935/72372133-cc5d2800-372b-11ea-8d51-ac0a240f377d.png)

**Comment by sarabs3** [comment]
`react-jss` is already present in the package.json file.
https://github.com/React-Chandigarh/reactchandigarh.dev/blob/master/package.json#L8

**Comment by sourabhgrover** [comment]
Is it working fine on your end.
I tried to install same package but getting above mentioned error.

**Comment by sarabs3** [comment]
I just did a fresh clone and install packages. It's working fine. 
Try to take the latest pull and make sure you are on the master branch.

Let me know if you are still getting the issue.

**Comment by sourabhgrover** [comment]
Thanks @sarabs3 
My forked master is updated let me try to reinstall packages.
In case of any concerns i will get back to you !!
